### ISSUE TITLE
Unable to handle request without a valid action parameter. Please supply a valid soap action

### ISSUE THREAD

**Issue by rafalkaczynsky** [magnatronus/ldbs-json#3]
Is this package works with Staff type? For User type works great but when switch to Staff then getting following error: 'Unable to handle request without a valid action parameter. Please supply a valid soap action'. 
Should I supply it?

**Comment by magnatronus** [comment]
It should be fine as I use it for a production mobile app that I currently distribute.  I guess the first question is do you have a valid Staff key (which will not be the same as the User one) ?

Also the params for Staff calls are not the same as the user ones (and they have different  required/optional attributes). I have also found that the document page for the API are not always accurate.

If you have not already I would suggest looking at the examples dir as there are a couple of Staff API calls - try those first and see if they work OK.
